package main

import (
	"encoding/json"
	"strconv"

	"github.com/fulldump/golax"
)

func main() {

	myApi := golax.NewApi()
	myApi.Prefix = "/service/v1"

	myApi.Root.
		Doc(golax.Doc{
			Description: `
				_Example_ is a demonstration REST API that implements a CRUD over a collection
				of users, stored in memory.

				All API calls:
				* are returning errors with the same JSON format and
				* are logging all request to standard output.
			`,
		}).
		Interceptor(golax.InterceptorLog).
		Interceptor(golax.InterceptorError)

	users := myApi.Root.Node("users").
		Doc(golax.Doc{
			Description: `
				Resource users to list and create elements. It does not support pagination,
				sorting or filtering.
			`}).
		Method("GET", getUsers, golax.Doc{
			Description: `
				Return a list with a list of user ids:

				´´´json
				[1,2,3]
				´´´
			`}).
		Method("POST", postUsers, golax.Doc{
			Description: `
				Create a user:
				´´´sh
				curl http://localhost:8000/service/v1/users --data '{"name": "John"}'
				´´´
				And return the user id:
				´´´json
				{"id":4}
				´´´
		`})

	users.Node("{user_id}").
		Doc(golax.Doc{
			Description: `
				Resource user to retrieve, modify and delete. A user has this structure:

				´´´json
				{
					"name": "Menganito Menganez",
					"age": 30,
					"introduction": "Hi, I like wheels and cars"
				}
				´´´
		`}).
		Interceptor(interceptorUser).
		Method("GET", getUser, golax.Doc{
			Description: `
				Return a user in JSON format. For example:
				´´´sh
				curl http://localhost:8000/service/v1/users/4
				´´´
				Will return this:
				´´´json
				{
					"name": "John",
					"age": 0,
					"introduction": ""
				}
				´´´
			`}).
		Method("POST", postUser, golax.Doc{
			Description: `
				Modify an existing user. You do not have to send all fields, for example, to
				change only the age of the user 4:

				´´´sh
				curl http://localhost:8000/service/v1/users/4 --data '{"age": 11}'
				´´´
			`}).
		Method("DELETE", deleteUser, golax.Doc{
			Description: `
				Delete an existing user:

				´´´sh
				curl -X DELETE http://localhost:8000/service/v1/users/4
				´´´
			`})

	//d := apidoc.Build(myApi, myApi.Root)
	//d.Title = "Example"
	//d.Subtitle = "Autogenerated doc"

	myApi.Serve()
}

func getUsers(c *golax.Context) {
	ids := []int{}
	for id := range users {
		ids = append(ids, id)
	}

	json.NewEncoder(c.Response).Encode(ids)
}

func postUsers(c *golax.Context) {
	u := &User{}

	json.NewDecoder(c.Request.Body).Decode(u)

	insert_user(u)

	c.Response.WriteHeader(201)
	json.NewEncoder(c.Response).Encode(map[string]interface{}{"id": u.id})
}

func getUser(c *golax.Context) {
	u := getContextUser(c)

	json.NewEncoder(c.Response).Encode(u)
}

func postUser(c *golax.Context) {
	u := getContextUser(c)

	json.NewDecoder(c.Request.Body).Decode(u)
}

func deleteUser(c *golax.Context) {
	u := getContextUser(c)
	delete(users, u.id)
}

/**
 * Interceptor {user_id}
 * if: `user_id` exists -> load the object and put it available in the context
 * else: raise 404
 */
var interceptorUser = &golax.Interceptor{
	Documentation: golax.Doc{
		Name: "User",
		Description: `
			Extract and validate user from url. If the user does not exist, a 404 will be
			returned.
		`,
	},
	Before: func(c *golax.Context) {
		userID, _ := strconv.Atoi(c.Parameter)
		if user, exists := users[userID]; exists {
			c.Set("user", user)
		} else {
			c.Error(404, "user `"+c.Parameter+"` does not exist")
		}
	},
}

/**
 * Helper to get a user object from the context
 */
func getContextUser(c *golax.Context) *User {
	v, _ := c.Get("user")
	return v.(*User)
}
